#!/bin/bash

BLACKLISTS_=${BLACKLISTS_:-"/usr/share/ssh/blacklist."}
RET_=0

check_fp() {
    file_="$1"
    out_=$(ssh-keygen -l -f "$file_")
    ret_=$?
    if [[ $ret_ != 0 ]]; then
        echo "ERROR: parsing ${file_} with ssh-keygen" >&2
        RET_=1
        return
    fi

    # split on whitespace and convert to array
    set -f
    # just WTF..., shell is really a useless pice of sh*t, don't use, really!!
    # shellcheck disable=SC2206
    IFS=" " outa_=($out_)
    set +f

    # get data from array
    BITS_=${outa_[0]}
    FP_=${outa_[1]}
    #CMT_=${outa_[2]}
    TYPE_=${outa_[3]}

    # convert fingerprint to data required for blacklist
    #   remove colons and remove the first 12 characters
    FP_HEX_=${FP_//:/}
    FP_HEX_SHORT_=${FP_HEX_:12}

    # clean up type information
    #   (RSA) -> RSA
    TYPE_=${TYPE_:1:-1}

    if grep -q "$FP_HEX_SHORT_" "${BLACKLISTS_}${TYPE_}-$BITS_"; then
        # we have a match AND thus a vulnerable key
        echo "$FP_ $file_ IS VULNERABLE"
        RET_=1
    else
        # we have no match
        #echo $BITS_ $FP_ $CMT_ >&2
        :
    fi
}

while (( $# != 0 )); do
    check_fp "$1"
    shift
done

exit $RET_
