name: CI

# Controls when the action will run. 
on:
  # don't trigger 2 times for a pull request
  push:
    branches: master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install shunit2
        run: sudo apt-get -y -q --no-install-recommends install shunit2 openssh-client openssh-blacklist openssh-blacklist-extra

      - name: Run shellcheck
        run: make check

      - name: Run tests
        run: make test
